version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=booking_system
